services:
  postgres:
    stop_grace_period: 30s
    stop_signal: SIGTERM
    container_name: postgres_container
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "devloredb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123Secret_a"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"               # Пробрасываем порт, чтобы можно было подключиться локально
    volumes:
      - devlore-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d devloredb" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - backend

  devloreapi:
    stop_grace_period: 30s
    stop_signal: SIGTERM
    container_name: devlore-api
    build:
      context: .
      dockerfile: DevLore/Dockerfile
    environment:
      - DB_HOST=postgres           # внутри сети контейнеров имя хоста = имя сервиса
      - POSTGRES_DB=devloredb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123Secret_a
      - APP_NAME=devlore
      - JWT_KEY=your-secret-key-at-least-32-characters-long   # добавим для аутентификации
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend

volumes:
  devlore-data:

networks:
  backend:
    driver: bridge